name: Welcome to Joel's personal site
description: Just a random stuff I want to post :/
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "http://joelimgu.github.io/"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Joel"
author-description: "Is this the only way to look at it?"

# Disqus config
disqus-shortname: ""
