name: Welcome to Joel's personal site
description: Just random stuff I want to post :/
meta_description: "Joel Imbergamo Guasch personal page"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "http://joelimgu.github.io/"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

permalink: /:collection/:day/:month/:year/:title

# Details for the RSS feed generator
url: ""
author: "Joel"
author-description: "Is this the only way to look at it?"

# Disqus config
disqus-shortname: ""
